branch-defaults:
  default:
    environment: torrentql-nextjs-production
environment-defaults:
  torrentql-nextjs-production:
    branch: null
    repository: null
global:
  application_name: torrentql-nextjs
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Docker running on
    64bit Amazon Linux/2.12.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
