- name: apply common configuration to all nodes
  hosts: all
  become: yes

  roles:
    - { role: common, tags: common }

- name: deploy deluge to deluge nodes
  hosts: deluge
  remote_user: ubuntu

  roles:
    - { role: deluge, tags: deluge }

- name: deploy nginx to deluge nodes
  hosts: deluge
  remote_user: ubuntu

  roles:
    - { role: nginx, tags: nginx }
