- name: apply common
  hosts: all
  become: yes

  roles:
    - { role: common, tags: common }

- name: apply nginx
  hosts: deluge
  remote_user: ubuntu

  roles:
    - { role: nginx, tags: nginx }

- name: apply deluge
  hosts: deluge
  remote_user: ubuntu

  roles:
    - { role: deluge, tags: deluge }
