kind: pipeline
name: default

steps:
- name: build-nextjs
  image: plugins/docker
  settings:
    repo: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-nextjs
    tags: latest
    context: packages/nextjs/
