pipeline:
  deploy-nextjs:
    group: deploy
    image: mitchellhuang/aws-ebcli
    commands:
      - cd packages/nextjs
      - eb deploy
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      branch: master
