pipeline:
  build-repo:
    image: node:8-alpine
    commands:
      - yarn --production
    when:
      branch: master

  build-nextjs:
    group: build
    image: node:8-alpine
    commands:
      - cd packages/nextjs
      - yarn --production
      - yarn build
      - cd lambda
      - yarn --production
    when:
      branch: master

  build-graphql:
    group: build
    image: node:8-alpine
    commands:
      - apk add --no-cache git
      - cd packages/graphql
      - yarn --production
    when:
      branch: master

  deploy:
    image: node:8-alpine
    commands:
      - yarn serverless deploy
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      branch: master
