kind: pipeline
name: default

steps:
- name: envsubst
  image: supinf/envsubst
  commands:
  - cd packages/deploy
  - export TAG=$DRONE_COMMIT_SHA
  - ./scripts/envsubst.sh kubernetes

- name: build-graphql
  image: plugins/ecr
  settings:
    registry: 392244324571.dkr.ecr.eu-west-1.amazonaws.com
    region: eu-west-1
    repo: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-graphql
    tags:
      - latest
      - "${DRONE_COMMIT_SHA}"
    context: packages/graphql/
    dockerfile: packages/graphql/Dockerfile
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
  depends_on:
  - envsubst

- name: build-nextjs
  image: plugins/ecr
  settings:
    registry: 392244324571.dkr.ecr.eu-west-1.amazonaws.com
    region: eu-west-1
    repo: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-nextjs
    tags:
      - latest
      - "${DRONE_COMMIT_SHA}"
    context: packages/nextjs/
    dockerfile: packages/nextjs/Dockerfile
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
  depends_on:
  - envsubst

- name: deploy-graphql
  image: lachlanevenson/k8s-kubectl
  environment:
    KUBE_CONFIG_FILE:
      from_secret: kube_config_file
  commands:
  - mkdir -p $HOME/.kube
  - echo $KUBE_CONFIG_FILE | base64 -d > $HOME/.kube/config
  - cd packages/deploy/kubernetes
  - kubectl apply -f graphql/deploy.yml
  - kubectl rollout status torrentql-graphql
  depends_on:
  - build-graphql
  - build-nextjs

- name: deploy-nextjs
  image: lachlanevenson/k8s-kubectl
  environment:
    KUBE_CONFIG_FILE:
      from_secret: kube_config_file
  commands:
  - mkdir -p $HOME/.kube
  - echo $KUBE_CONFIG_FILE | base64 -d > $HOME/.kube/config
  - cd packages/deploy/kubernetes
  - kubectl apply -f nextjs/deploy.yml
  - kubectl rollout status torrentql-nextjs
  depends_on:
  - deploy-graphql
