kind: pipeline
name: default

steps:
- name: envsubst
  image: supinf/envsubst
  commands:
  - cd deploy
  - export TAG=$DRONE_COMMIT_SHA
  - ./scripts/envsubst.sh kubernetes
  when:
    branch:
    - master

- name: build-graphql
  image: plugins/ecr
  settings:
    registry: 392244324571.dkr.ecr.eu-west-1.amazonaws.com
    region: eu-west-1
    repo: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-graphql
    tags:
      - latest
      - "${DRONE_COMMIT_SHA}"
    context: ./
    dockerfile: packages/graphql/Dockerfile
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
  depends_on:
  - envsubst
  when:
    branch:
    - master

- name: build-nextjs
  image: plugins/ecr
  settings:
    registry: 392244324571.dkr.ecr.eu-west-1.amazonaws.com
    region: eu-west-1
    repo: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-nextjs
    tags:
      - latest
      - "${DRONE_COMMIT_SHA}"
    context: ./
    dockerfile: packages/nextjs/Dockerfile
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
  depends_on:
  - envsubst
  when:
    branch:
    - master

- name: deploy-graphql
  image: lachlanevenson/k8s-kubectl
  environment:
    DIGITALOCEAN_ACCESS_TOKEN:
      from_secret: digitalocean_access_token
  commands:
  - apk add --no-cache curl
  - curl -sL https://github.com/digitalocean/doctl/releases/download/v1.22.0/doctl-1.22.0-linux-amd64.tar.gz | tar -xzv
  - mv doctl /usr/local/bin/
  - doctl kubernetes cluster kubeconfig save tql-k8s-staging
  - kubectl apply -f deploy/kubernetes/graphql/deploy.yml
  - kubectl rollout status deployment torrentql-graphql
  depends_on:
  - build-graphql
  - build-nextjs
  when:
    branch:
    - master

- name: deploy-nextjs
  image: lachlanevenson/k8s-kubectl
  environment:
    DIGITALOCEAN_ACCESS_TOKEN:
      from_secret: digitalocean_access_token
  commands:
  - apk add --no-cache curl
  - curl -sL https://github.com/digitalocean/doctl/releases/download/v1.22.0/doctl-1.22.0-linux-amd64.tar.gz | tar -xzv
  - mv doctl /usr/local/bin/
  - doctl kubernetes cluster kubeconfig save tql-k8s-staging
  - kubectl apply -f deploy/kubernetes/nextjs/deploy.yml
  - kubectl rollout status deployment torrentql-nextjs
  depends_on:
  - deploy-graphql
  when:
    branch:
    - master

- name: notify-slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: alerts
  depends_on:
  - deploy-graphql
  - deploy-nextjs
