kind: pipeline
name: default

steps:
- name: build-repo
  image: node:8-alpine
  commands:
  - yarn --production
  when:
    branch:
    - master
    - production

- name: build-nextjs
  image: node:8-alpine
  commands:
  - cd packages/nextjs
  - yarn --production
  - yarn build
  - cd lambda
  - yarn --production
  depends_on:
  - build-repo
  when:
    branch:
    - master
    - production

- name: build-graphql
  image: node:8-alpine
  commands:
  - apk add --no-cache git
  - cd packages/graphql
  - yarn
  - yarn build
  - yarn --production
  depends_on:
  - build-repo
  when:
    branch:
    - master
    - production

- name: deploy-staging
  image: node:8-alpine
  commands:
  - yarn serverless deploy
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  depends_on:
  - build-nextjs
  - build-graphql
  when:
    branch:
    - master

- name: deploy-production
  image: node:8-alpine
  commands:
  - yarn serverless deploy --stage production --domain torrentql.com
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  depends_on:
  - build-nextjs
  - build-graphql
  when:
    branch:
    - production
