kind: pipeline
name: default

steps:
- name: build-nextjs
  image: plugins/ecr
  settings:
    registry: 392244324571.dkr.ecr.eu-west-1.amazonaws.com
    region: eu-west-1
    repo: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-nextjs
    tags:
      - latest
      - "${DRONE_COMMIT_SHA:0:8}"
    context: packages/nextjs/
    dockerfile: packages/nextjs/Dockerfile
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
