pipeline:
  build-repo:
    group: build
    image: node:8-alpine
    commands:
      - yarn

  build-nextjs:
    group: build
    image: node:8-alpine
    commands:
      - cd packages/nextjs
      - yarn
      - yarn build

  build-graphql:
    group: build
    image: node:8
    commands:
      - cd packages/graphql
      - yarn

  deploy:
    image: node:8-alpine
    commands:
      - apk add --no-cache gettext
      - yarn global add serverless
      - ./packages/deploy/scripts/envsubst.sh ./serverless.yml
      - serverless deploy
    secrets: [ aws_access_key_id, aws_secret_access_key ]
