pipeline:
  bootstrap:
    group: build
    image: node:10-alpine
    commands:
      - yarn
      - yarn bootstrap
    when:
      branch: master

  build-nextjs:
    group: build
    image: node:10-alpine
    commands:
      - cd packages/nextjs
      - yarn build
    when:
      branch: master

  build-graphql:
    group: build
    image: node:10-alpine
    commands:
      - cd packages/graphql
    when:
      branch: master

  deploy:
    image: node:10-alpine
    commands:
      - yarn serverless deploy
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      branch: master
