kind: pipeline
name: default

steps:
- name: build-nextjs
  image: plugins/docker
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  settings:
    registry: 392244324571.dkr.ecr.eu-west-1.amazonaws.com
    repo: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-nextjs
    tags: latest
    context: packages/nextjs/
    dockerfile: packages/nextjs/Dockerfile
