apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  labels:
    app: torrentql
    tier: billing
data:
  NODE_ENV: production
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASE: "${DB_DATABASE}"
  DB_SSL: "${DB_SSL}"
