apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: torrentql-billing
spec:
  selector:
    matchLabels:
      app: torrentql
      tier: billing
  replicas: 1
  template:
    metadata:
      labels:
        app: torrentql
        tier: billing
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
      - name: billing
        image: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-billing:${TAG}
        envFrom:
          - configMapRef:
              name: billing-config
