apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: ip-space
      protocol: layer2
      addresses:
      - 37.187.144.135-37.187.144.135
