version: '3.3'
services:
  deluge:
    image: "linuxserver/deluge"
    restart: "always"
    environment:
      - PGID=0
      - PUID=0
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
    volumes:
      - "/Users/Jkofsky/Downloads:/root/Downloads"
