apiVersion: v1
kind: Service
metadata:
  name: torrentql-nextjs
spec:
  type: ClusterIP
  selector:
    app: torrentql
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
