apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: torrentql-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: staging.torrentql.com
    http:
      paths:
      - path: /
        backend:
          serviceName: torrentql-nextjs
          servicePort: 80
      - path: /graphql
        backend:
          serviceName: torrentql-graphql
          servicePort: 80
  tls:
  - hosts:
    - staging.torrentql.com
    secretName: torrentql-tls
