apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: torrentql-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: staging.torrentql.com
    http:
      paths:
      - path: /
        backend:
          serviceName: torrentql-nextjs
          servicePort: 80
      - path: /graphql
        backend:
          serviceName: torrentql-graphql
          servicePort: 80
