apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-config
  labels:
    app: torrentql
    tier: backend
data:
  NODE_ENV: production
  DB_HOST: postgres.default.svc.cluster.local
  DB_USER: torrentql
  DB_PASSWORD: run
  DB_DATABASE: torrentql
  JWT_SECRET: abcdef
