apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: torrentql-graphql
spec:
  selector:
    matchLabels:
      app: torrentql
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: torrentql
        tier: backend
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
      - name: graphql
        image: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-graphql:latest
        ports:
          - containerPort: 3001
        envFrom:
          - configMapRef:
              name: graphql-config
