apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: torrentql-nextjs
spec:
  selector:
    matchLabels:
      app: torrentql
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: torrentql
        tier: frontend
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
      - name: nextjs
        image: 392244324571.dkr.ecr.eu-west-1.amazonaws.com/torrentql-nextjs:${TAG}
        ports:
          - containerPort: 3001
        envFrom:
          - configMapRef:
              name: nextjs-config
