- hosts: all
  become: yes
  tasks:
    - name: install docker
      apt:
        name: docker.io=18.09*
        state: present
        update_cache: true

    - name: create docker daemon.json
      copy:
        src: files/daemon.json
        dest: /etc/docker/daemon.json

    - name: restart docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

    - name: add user ubuntu to group docker
      user:
        name: ubuntu
        groups: docker
        append: yes
