version: '3.3'
services:
  deluge:
    image: "linuxserver/deluge"
    restart: "always"
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
      - "58946:58946/udp"
