- name: create deluge config directory
  become: yes
  file:
    path: /config
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775

- name: create deluge data directory
  become: yes
  file:
    path: /downloads
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775
