- name: create data directory
  become: yes
  file:
    path: /config
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775

- name: create data directory
  become: yes
  file:
    path: /downloads
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775

- name: run deluge container
  docker_container:
    image: linuxserver/deluge
    name: deluge
    state: started
    restart_policy: always
    env:
      PUID: "1000"
      PGID: "1000"
      VIRTUAL_HOST: "gra000-deluge.eu-west-1.torrentql.com"
      VIRTUAL_PORT: "8112"
      LETSENCRYPT_HOST: "gra000-deluge.eu-west-1.torrentql.com"
    ports:
      - "8112:8112"
      - "58846:58846"
      - "58946:58946"
    volumes:
      - /config:/config
      - /downloads:/downloads
