- name: create conf.d directory
  become: yes
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: create certs directory
  become: yes
  file:
    path: /etc/nginx/certs
    state: directory

- name: create vhost.d directory
  become: yes
  file:
    path: /etc/nginx/vhost.d
    state: directory

- name: create share directory
  become: yes
  file:
    path: /usr/share/nginx/html
    state: directory

- name: copy default.conf to conf.d directory
  copy:
    src: files/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: run nginx-proxy container
  docker_container:
    image: jwilder/nginx-proxy
    name: nginx-proxy
    state: started
    restart_policy: always
    network_mode: host
    env:
      DEFAULT_HOST: "gra000.eu-west-1.torrentql.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

- name: run letsencrypt-nginx-proxy-companion container
  docker_container:
    image: jrcs/letsencrypt-nginx-proxy-companion
    name: nginx-proxy-letsencrypt
    state: started
    restart_policy: always
    env:
      DEFAULT_EMAIL: mitchell@mitchellhuang.net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

- name: run nginx-files container
  docker_container:
    image: nginx
    name: nginx-files
    state: started
    restart_policy: always
    env:
      VIRTUAL_HOST: "gra000.eu-west-1.torrentql.com"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "gra000.eu-west-1.torrentql.com"
    volumes:
      - /downloads:/downloads
      - /etc/nginx/conf.d:/etc/nginx/conf.d
