- name: create conf.d directory
  become: yes
  file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root

- name: copy default.conf to conf.d directory
  copy:
    src: files/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: run nginx container
  docker_container:
    image: nginx:latest
    name: nginx
    state: started
    restart: yes
    restart_policy: always
    network_mode: host
    volumes:
      - /data:/data
      - /etc/nginx/conf.d:/etc/nginx/conf.d
