- name: create nginx conf.d directory
  become: yes
  file:
    path: /var/torrentql/nginx/conf.d
    state: directory

- name: create nginx certs directory
  become: yes
  file:
    path: /var/torrentql/nginx/certs
    state: directory

- name: create nginx vhost.d directory
  become: yes
  file:
    path: /var/torrentql/nginx/vhost.d
    state: directory

- name: create nginx share directory
  become: yes
  file:
    path: /var/torrentql/nginx/html
    state: directory

- name: copy nginx default.conf
  copy:
    src: files/default.conf
    dest: /var/torrentql/nginx/conf.d/default.conf
