apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: s001.torrentql.com
    http:
      paths:
      - path: /
        backend:
          serviceName: torrentql-nextjs
          servicePort: 80
