apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-config
  labels:
    app: torrentql
    tier: backend
data:
  NODE_ENV: production
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASE: "${DB_DATABASE}"
  DB_SSL: "${DB_SSL}"
  JWT_SECRET: "${JWT_SECRET}"
  FRONTEND_HOST: "${FRONTEND_HOST}"
  OPENNODE_API_KEY: "${OPENNODE_API_KEY}"
  SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
