apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-config
  labels:
    app: torrentql
    tier: backend
data:
  NODE_ENV: ""
  DB_HOST: ""
  DB_PORT: ""
  DB_USER: ""
  DB_PASSWORD: ""
  DB_DATABASE: ""
  DB_SSL: ""
  JWT_SECRET: ""
