apiVersion: v1
kind: Service
metadata:
  name: torrentql-graphql
spec:
  type: ClusterIP
  selector:
    app: torrentql
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
