kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deluge-pvc
  labels:
    app: deluge
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
